name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploy everything to production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@$EC2_HOST << 'EOF'
            cd canvasflow && \
            git pull origin main && \
            export PATH=/home/ubuntu/.nvm/versions/node/v22.17.1/bin:$PATH && \
            npm install -g pnpm && \
            pnpm install && \
            pnpm run build && \
            pm2 restart frontend && \
            pm2 restart http-backend && \
            pm2 restart wb-backend
          EOF
